# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplauction', '0003_auto_20160305_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
